server:
  port: ${server.port}

spring:
  cloud:
    bus:
      enabled: ${spring.cloud.bus.enabled}
      trace:
        enabled: ${spring.cloud.bus.trace.enabled}
  rabbitmq:
    host: ${spring.rabbitmq.host}
    port: ${spring.rabbitmq.port}
    username: ${spring.rabbitmq.username}
    password: ${spring.rabbitmq.password}
  sleuth:
    sampler:
      probability: ${spring.sleuth.sampler.probability}
  zipkin:
    base-url: ${spring.zipkin.base-url}
    sender:
      type: ${spring.zipkin.sender.type}

management:
  endpoints:
    web:
      exposure:
        include: ${management.endpoints.web.exposure.include}
      cors:
        allowed-origins: ${management.endpoints.web.cors.allowed-origins}
        allowed-methods: ${management.endpoints.web.cors.allowed-methods}
feign:
  hystrix:
    enabled: ${feign.hystrix.enabled}
