server:
  port: 8774

spring:
  application:
    name: ConfigClientBus
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: wulibao
    password: caidao

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/