foo: ConfigClientBus-dev.v10
server:
  port: 9011
spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: wulibao
    password: caidao

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"