server:
  port: 8769

spring:
  application:
    name: Zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    ribbon:
      path: /Ribbon/**
      serviceId: Ribbon

    feign:
      path: /Feign/**
      serviceId: Feign

    zipkin-a:
      path: /Zipkin-a/**
      serviceId: Zipkin-a

    zipkin-b:
      path: /Zipkin-b/**
      serviceId: Zipkin-b